#Summary

* [Getting Started](manual/index.md)
 - [Technical Concepts](manual/gettingstarted/concepts.md)
 - [KAP Release Notes](manual/release_notes.md)
 - [Events and Conferences](manual/gettingstarted/events.md)
 - [Community Best Practices](manual/gettingstarted/best_practices.md)
 - [Terminology](manual/gettingstarted/terminology.md)
 - [FAQ](manual/gettingstarted/faq.md)
* [Installation](manual/install/index.md)
 - [Hadoop Enviroument](/manual/install/hadoop_evn.md)
 - [Deploy in cluster mode](/manual/install/kylin_cluster.md)
 - [Advance Settings](/manual/install/advance_settings.md)

* [Tutorial](manual/tutorial/kylin_sample.md)
 - [Quick Start with Sample Cube](manual/tutorial/kylin_sample.md)
 - [KAP Cube Creation](manual/tutorial/create_cube.md)
 - [KAP Cube Build and Job Monitoring](manual/tutorial/cube_build_job.md)
 - [KAP Cube Permission](manual/tutorial/acl.md)
 - [KAP Web Interface](manual/tutorial/web.md)
 - [Tableau 8](manual/tutorial/tableau.md)
 - [Tableau 9](manual/tutorial/tableau_91.md)
 - [MS Excel and Power BI](manual/tutorial/powerbi.md)
 - [KAP ODBC Driver](manual/tutorial/odbc.md)
* [How to](manual/howto/howto_build_cube_with_restapi.md)
 - [Build Cube with RESTful API](manual/howto/howto_build_cube_with_restapi.md)
 - [Use RESTful API in Javascript](manual/howto/howto_use_restapi_in_js.md)
 - [Use RESTful API](manual/howto/howto_use_restapi.md)
 - [Optimize Cube](manual/howto/howto_optimize_cubes.md)
 - [Backup Metadata](manual/howto/howto_backup_metadata.md)
 - [Cleanup Storage(HDFS&HBase Tables)](manual/howto/howto_cleanup_storage.md)
 - [Use KAP Remote JDBC Driver](manual/howto/howto_jdbc.md)
 - [Upgrade from old versions](manual/howto/howto_upgrade.md)
 - [Enable Security with LDAP and SSO](manual/howto/howto_ldap_and_sso.md)
 - [How to Update HBase Coprocessor](manual/howto/howto_update_coprocessor.md)
